### ISSUE TITLE
Question: Android PhotoSync "Expected 207 MultiStatus got 200" 

### ISSUE THREAD

**Issue by Mbd06b** [p80n/photoprism-helm#10]
Hey this is an in-kind question for other users of this helm chart, not a bug.

I got Photoprism launched, and can access UI and everything seems to be working. 
![image](https://github.com/p80n/photoprism-helm/assets/12649222/46405548-30d3-4be7-9616-1ed05e3c872b)
PhotoPrism® build 211215-93b26f19-Linux-x86_64

I'm trying to enable PhotoSync from Android as described by these instructions here, but have run into a blocker: 
https://docs.photoprism.app/user-guide/sync/mobile-devices/

When I put in my credentials, I can't connect, with PhotoSync reponding "**Expected 207 MultiStatus got 200"**.  In this screen here: 
![image](https://github.com/p80n/photoprism-helm/assets/12649222/584a8336-21d7-4a13-ab0b-2333074a4cce)

I currently suspect e a possible misconfiguration of nginx, because 200 is an OK status, but 207 might suggest that it's expecting some kind of wss AND http based connection to be seen and I have a suspicion that might be the problem.  I based my ingress annotations from this example here: 
See Here, https://docs.photoprism.app/getting-started/proxies/nginx/

Here's what I currently have: 
```
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: public
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/websocket-services: "photoprism"
    nginx.ingress.kubernetes.io/proxy-body-size: "500M"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $host;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_http_version 1.1;
      proxy_buffering off;
```

Has anyone experienced this issue, or might share what ingress annotations they are using to troubleshoot or try other configs.  Links to other issues?  Any help would be appreciated.

**Comment by Mbd06b** [comment]
I got it working by

updating to the latest photoprism-ce tag, and used this chart from @MichaelSp 's fork.
https://github.com/MichaelSp/photoprism-helm   

Then simplified my ingress: 
```
ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/websocket-services: "photoprism"
    nginx.ingress.kubernetes.io/proxy-body-size: "500M"

  className: public
  hosts:
  - host: photos.ethosengine.com
    paths:
    - path: /
      pathType: Prefix
  tls:
  - hosts:
    - photos.ethosengine.com
    secretName: photoprism-tls
```
